# Generated by Django 3.1.2 on 2020-11-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('editora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Editora')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('tipo_obra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de obra')),
                ('d_inicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data inicio')),
                ('documento', models.FileField(null=True, upload_to='media', verbose_name='Documento')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
            ],
        ),
    ]
