# Generated by Django 3.1.2 on 2020-12-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha'),
        ),
    ]
